### ISSUE TITLE
Compatible with PEP8

### ISSUE THREAD

**Issue by maksim77** [gomex/docker-zabbix#10]
I believe that the final code should be tested for compliance with [PEP8](https://www.python.org/dev/peps/pep-0008/).

**Comment by gomex** [comment]
Using [pep8](https://github.com/jcrocholl/pep8), I am working on it.

**Comment by maksim77** [comment]
Hi!
I spent all that time in the hospital and therefore could not continue to participate in the development. Who'll take care of chores at work, see what has been done and will continue!

**Comment by gomex** [comment]
Fixed with new commit dadd0b37bfcf1b32dd0c53c575c3c7768a861c55
