### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by maksim77** [gomex/docker-zabbix#11]

**Comment by gomex** [comment]
@maksim77 can please you do that?

**Comment by gomex** [comment]
I working on it now

**Comment by gomex** [comment]
I am stuck here: https://github.com/blacked/py-zabbix/issues/13

**Comment by gomex** [comment]
Solved! I need accept my PR, but my code is ok :)

https://github.com/blacked/py-zabbix/pull/15
