### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by maksim77** [gomex/docker-zabbix#13]
It seems to me that in the current implementation of the file README it is probably redundant. There is no need to describe things like install zabbix-agent. If a person is interested in the monitoring of containers it is unlikely that he needs to explain such simple concepts. My plan is to add a translation to Russian, not sure but it may be in German.

**Comment by gomex** [comment]
You are correct, but this repeated information is not a real problem, right? We can assume that is just a advice to avoid problem with initial test. What you think about it @maksim77 ?
